apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-furniture-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-furniture-postgres
  template:
    metadata:
      labels:
        app: go-furniture-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: gofurniture
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres